#include "util.h"

int read_status(struct rl_status* status) {
	
	// map shared memory
	int shm_id = shmget(SHMEM_KEY, sizeof(struct rl_status), SHMEM_PERMISSIONS);
	struct rl_status* shm_status = (struct rl_status*) shmat(shm_id, NULL, 0);
	
	if (shm_status == (void *) -1) {
		rl_log(ERROR, "failed to map shared status memory");
		return FAILURE;
	}
	
	// read status
	*status = *shm_status;
	
	// unmap shared memory
	shmdt(shm_status);
	
	return SUCCESS;
}

int write_status(struct rl_status* status) {
	
	// map shared memory
	int shm_id = shmget(SHMEM_KEY, sizeof(struct rl_status), IPC_CREAT | SHMEM_PERMISSIONS);
	struct rl_status* shm_status = (struct rl_status*) shmat(shm_id, NULL, 0);
	
	if (shm_status == (void *) -1) {
		rl_log(ERROR, "failed to map shared status memory");
		return FAILURE;
	}
	
	// write status
	*shm_status = *status;
	
	// unmap shared memory
	shmdt(shm_status);
	
	return SUCCESS;
}


/**
 * Count the number of bits set in an integer.
 * @param x
 * @return Number of bits.
 */
int count_bits(int x) {
	int MASK = 1;
	int i;
	int sum = 0;
	for (i=0;i<32;i++) {
		if ((x&MASK) > 0) {
			sum = sum + 1;
		}
		MASK = MASK << 1;
	}
	return sum;
}


/**
 * Integer division with ceiling.
 * @param n Numerator
 * @param d Denominator
 * @return Result
 */
int ceil_div(int n, int d) {
	if(n%d == d || n%d == 0) {
		return n/d;
	} else {
		return n/d + 1;
	}
}

/**
 * Non-blocking terminal I/O: Check if the user pressed "Enter".
 * TODO: remove
 * @return 1 if button pressed.
 */
int input_available() {
  struct timeval tv;
  fd_set fds;
  tv.tv_sec = 0;
  tv.tv_usec = 0;
  FD_ZERO(&fds);
  FD_SET(STDIN_FILENO, &fds);
  select(STDIN_FILENO+1, &fds, NULL, NULL, &tv);
  return (FD_ISSET(0, &fds));
}

// ------------------------------ SIGNAL HANDLER ------------------------------ //

void sig_handler(int signo) { // TODO: combine?

	// signal generated by stop function
    if (signo == SIGQUIT) {
		// stop sampling
		status.state = RL_OFF; 
	}

    // Ctrl+C handling
    if (signo == SIGINT) {
    	signal(signo, SIG_IGN);
    	printf("Stopping RocketLogger ...\n");
    	status.state = RL_OFF;
    }
}
// TODO: allow forced Ctrl+C

// ------------------------------ MEMORY MAP/UNMAP ------------------------------ // TODO: move to pru

// map physical memory into virtual adress space
void* memory_map(unsigned int addr, size_t size) {
	// memory file
	int fd;
	if((fd = open("/dev/mem", O_RDWR | O_SYNC)) == -1){
		rl_log(ERROR, "failed to open /dev/mem");
		return NULL;
    }
	
	// map shared memory into userspace
	off_t target = addr;
	void* map_base = mmap(0, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, target & ~MAP_MASK);
    if(map_base == (void *) -1) {
		rl_log(ERROR, "failed to map base address");
		return NULL;
    }
		
	close(fd);
	
	return map_base;
}

// unmap the mapped memory
int memory_unmap(void* ptr, size_t size) {
	if(munmap(ptr, size) == -1) {
		rl_log(ERROR, "failed to unmap memory");
		return FAILURE;
    }
    
	return SUCCESS;
}

// ------------------------------ FILE READING/WRITING  ------------------------------ //

// reading integer from file
int read_file_value(char filename[]) {
	FILE* fp;
	unsigned int value = 0;
	fp = fopen(filename, "rt");
	if (fp < 0) {
		rl_log(ERROR, "failed to open file");
		return FAILURE;
	}
	if(fscanf(fp, "%x", &value) < 0) {
		rl_log(ERROR, "failed to read from file");
		return FAILURE;
	}
	fclose(fp);
	return value;
}


// ------------------------------ LOG HANDLING ------------------------------ //

int log_created = 0;

void rl_log(rl_log_type type, const char* format, ... ) {
	
	// open/init file
	FILE* log_fp;
	if(log_created == 0) {
		log_created = 1;
		log_fp = fopen(LOG_FILE, "w");
		fprintf(log_fp, "--- RocketLogger Log File ---\n\n");
	} else {
		log_fp = fopen(LOG_FILE, "a");
	}
	
	// print date/time
	struct timeval current_time;
	gettimeofday(&current_time, NULL);
	time_t nowtime = current_time.tv_sec;
	fprintf(log_fp, "  %s", ctime(&nowtime));
	
	// get arguments
	va_list args;
	va_start(args, format);
	
	// print error message
	if(type == ERROR) {
		
		// file
		fprintf(log_fp, "     Error: ");
		vfprintf(log_fp, format, args);
		fprintf(log_fp, "\n");
		// terminal
		printf("Error: ");
		vprintf(format, args);
		printf("\n\n");
		
	} else if(type == WARNING) {
		
		// file
		fprintf(log_fp, "     Warning: ");
		vfprintf(log_fp, format, args);
		fprintf(log_fp, "\n");
		// terminal
		printf("Warning: ");
		vprintf(format, args);
		printf("\n\n");
		
	} else if(type == INFO) {
		
		fprintf(log_fp, "     Info: ");
		vfprintf(log_fp, format, args);
		fprintf(log_fp, "\n");
		
	} else {
		// for debugging purposes
		printf("Error: wrong error-code\n");
	}
	
	// facilitate return
	va_end(args);
	
	// close file
	fflush(log_fp);
	fclose(log_fp);
}