stages:
  - build
  - test
  - deploy
  
doxygen:
  stage: deploy
  script:
  - which doxygen
  - doxygen code/src/Doxyfile
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  only:
  - master
