RocketLogger: rl_sensor Struct Reference
rl_sensor Struct Reference
#include <sensor.h>
Data Fields
char name [SENSOR_NAME_LENGTH]
int identifier
int channel
rl_unit_t unit
int32_t scale
int(* init)(int)
void(* deinit)(int)
int(* read)(int)
int32_t(* get_value)(int, int)
Detailed Description
Standardized RL sensor interface definition
Definition at line 54 of file sensor.h.
Field Documentation
channel
int rl_sensor::channel
Definition at line 57 of file sensor.h.
deinit
void(* rl_sensor::deinit) (int)
Definition at line 61 of file sensor.h.
Referenced by sensors_close().
get_value
int32_t(* rl_sensor::get_value) (int, int)
Definition at line 63 of file sensor.h.
Referenced by sensors_read().
identifier
int rl_sensor::identifier
Definition at line 56 of file sensor.h.
Referenced by sensors_read(), and sensors_scan().
init
int(* rl_sensor::init) (int)
Definition at line 60 of file sensor.h.
Referenced by sensors_scan().
name
char rl_sensor::name[SENSOR_NAME_LENGTH]
Definition at line 55 of file sensor.h.
Referenced by rl_file_setup_ambient_channels().
read
int(* rl_sensor::read) (int)
Definition at line 62 of file sensor.h.
Referenced by sensors_read().
scale
int32_t rl_sensor::scale
Definition at line 59 of file sensor.h.
Referenced by rl_file_setup_ambient_channels().
unit
rl_unit_t rl_sensor::unit
Definition at line 58 of file sensor.h.
Referenced by rl_file_setup_ambient_channels().
The documentation for this struct was generated from the following file:
sensor/sensor.h