RocketLogger: rocketlogger.c File Reference
rocketlogger.c File Reference
#include <argp.h>
#include <ctype.h>
#include <error.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <linux/limits.h>
#include <unistd.h>
#include "log.h"
#include "rl.h"
#include "rl_lib.h"
#include "version.h"
Data Structures
struct arguments
Macros
#define ARGP_ARGUMENTS_COUNT 1
#define OPT_FILE_SIZE 1
#define OPT_SAMPLES_COUNT 2
#define OPT_SET_DEFAULT 3
#define OPT_RESET_DEFAULT 4
#define OPT_CALIBRATION 5
#define OPT_JSON 6
#define OPT_CLI 7
#define OPT_STREAM 8
Functions
int main (int argc, char *argv[])
Variables
const char * argp_program_version = "RocketLogger Command Line Interface"
const char * argp_program_bug_address = "<https://github.com/ETHZ-TEC/RocketLogger/issues>"
void(* argp_program_version_hook)(FILE *, struct argp_state *) = print_version
Macro Definition Documentation
ARGP_ARGUMENTS_COUNT
#define ARGP_ARGUMENTS_COUNT 1
Copyright (c) 2016-2020, ETH Zurich, Computer Engineering Group All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. Number of arguments to parse
Definition at line 51 of file rocketlogger.c.
OPT_CALIBRATION
#define OPT_CALIBRATION 5
Definition at line 61 of file rocketlogger.c.
OPT_CLI
#define OPT_CLI 7
Definition at line 65 of file rocketlogger.c.
OPT_FILE_SIZE
#define OPT_FILE_SIZE 1
Definition at line 53 of file rocketlogger.c.
OPT_JSON
#define OPT_JSON 6
Definition at line 63 of file rocketlogger.c.
OPT_RESET_DEFAULT
#define OPT_RESET_DEFAULT 4
Definition at line 59 of file rocketlogger.c.
OPT_SAMPLES_COUNT
#define OPT_SAMPLES_COUNT 2
Definition at line 55 of file rocketlogger.c.
OPT_SET_DEFAULT
#define OPT_SET_DEFAULT 3
Definition at line 57 of file rocketlogger.c.
OPT_STREAM
#define OPT_STREAM 8
Definition at line 67 of file rocketlogger.c.
Function Documentation
main()
int main (int argc, char * argv[])
Main RocketLogger binary, controls the sampling
Parameters
argc Number of input arguments
argv Input arguments
Returns
standard Linux return codes
Definition at line 241 of file rocketlogger.c.
References arguments::args, arguments::cli, arguments::config, arguments::config_reset, arguments::config_set_default, arguments::json, rl_config_print(), rl_config_print_cmd(), rl_config_print_json(), rl_config_read_default(), rl_config_reset(), rl_config_validate(), rl_config_write_default(), rl_get_status(), rl_is_sampling(), rl_log(), RL_LOG_ERROR, RL_LOG_IGNORE, RL_LOG_INFO, rl_log_init(), RL_LOG_VERBOSE, RL_LOG_WARNING, rl_run(), rl_status_print(), rl_status_print_json(), rl_stop(), arguments::silent, and arguments::verbose.
Variable Documentation
argp_program_bug_address
const char* argp_program_bug_address = "<https://github.com/ETHZ-TEC/RocketLogger/issues>"
Bug report address output for GNU standard command line format compliance.
Definition at line 77 of file rocketlogger.c.
argp_program_version
const char* argp_program_version = "RocketLogger Command Line Interface"
Program version output for GNU standard command line format compliance.
Definition at line 72 of file rocketlogger.c.
argp_program_version_hook
void(* argp_program_version_hook) (FILE *, struct argp_state *) (FILE * , struct argp_state *) = print_version
The argp program version print function hook
Definition at line 217 of file rocketlogger.c.