[scale, off] = rl_calibrate(...
    rl_read_bin('C:\Users\user\Desktop\data\calibrationV.dat',0), ...
    rl_read_bin('C:\Users\user\Desktop\data\20161012_cal_no_m_i1l.dat',0), ...
    rl_read_bin('C:\Users\user\Desktop\data\cal_ch1_i_mid.dat',1), ...
    rl_read_bin('C:\Users\user\Desktop\data\calibrationI1H.dat',0), ...
    rl_read_bin('C:\Users\user\Desktop\data\20161012_cal_no_m_i2l.dat',0), ...
    rl_read_bin('C:\Users\user\Desktop\data\cal_i2_mid_new2.dat',0), ...
    rl_read_bin('C:\Users\user\Desktop\data\calibrationI2H.dat',0), ...
    1);
