[scale, off] = rl_calibrate(...
    rl_read_bin('C:\Users\user\Desktop\data\20160915_cal_v.dat',0), ...
    rl_read_bin('C:\Users\user\Desktop\data\20160901_cal_i1l.dat',0), ...
    rl_read_bin('C:\Users\user\Desktop\data\cal_ch1_i_mid.dat',1), ...
    rl_read_bin('C:\Users\user\Desktop\data\20160901_cal_i1h.dat',0), ...
    rl_read_bin('C:\Users\user\Desktop\data\20160901_cal_i2l.dat',0), ...
    rl_read_bin('C:\Users\user\Desktop\data\cal_i2_mid_new2.dat',0), ...
    rl_read_bin('C:\Users\user\Desktop\data\20160901_cal_i2h.dat',0), ...
    1);
