var files_dup =
[
    [ "overlay", "dir_92138d61cc8b065dbc1f6442ab054d9d.html", null ],
    [ "pru", "dir_e177327a88fa486102a9bda16c7c5749.html", "dir_e177327a88fa486102a9bda16c7c5749" ],
    [ "sensor", "dir_59f484095bcddb1b5c7cfcc1ba766bc2.html", "dir_59f484095bcddb1b5c7cfcc1ba766bc2" ],
    [ "tests", "dir_59425e443f801f1f2fd8bbe4959a3ccf.html", null ],
    [ "calibration.c", "calibration_8c.html", "calibration_8c" ],
    [ "calibration.h", "calibration_8h.html", "calibration_8h" ],
    [ "gpio.c", "gpio_8c.html", "gpio_8c" ],
    [ "gpio.h", "gpio_8h.html", "gpio_8h" ],
    [ "gpiod_test.c", "gpiod__test_8c.html", "gpiod__test_8c" ],
    [ "log.c", "log_8c.html", "log_8c" ],
    [ "log.h", "log_8h.html", "log_8h" ],
    [ "meter.c", "meter_8c.html", "meter_8c" ],
    [ "meter.h", "meter_8h.html", "meter_8h" ],
    [ "pru.c", "pru_8c.html", "pru_8c" ],
    [ "pru.h", "pru_8h.html", "pru_8h" ],
    [ "rl.c", "rl_8c.html", "rl_8c" ],
    [ "rl.h", "rl_8h.html", "rl_8h" ],
    [ "rl_file.c", "rl__file_8c.html", "rl__file_8c" ],
    [ "rl_file.h", "rl__file_8h.html", "rl__file_8h" ],
    [ "rl_hw.c", "rl__hw_8c.html", "rl__hw_8c" ],
    [ "rl_hw.h", "rl__hw_8h.html", "rl__hw_8h" ],
    [ "rl_lib.c", "rl__lib_8c.html", "rl__lib_8c" ],
    [ "rl_lib.h", "rl__lib_8h.html", "rl__lib_8h" ],
    [ "rl_socket.c", "rl__socket_8c.html", "rl__socket_8c" ],
    [ "rl_socket.h", "rl__socket_8h.html", "rl__socket_8h" ],
    [ "rocketlogger.c", "rocketlogger_8c.html", "rocketlogger_8c" ],
    [ "rocketloggerd.c", "rocketloggerd_8c.html", "rocketloggerd_8c" ],
    [ "sem.c", "sem_8c.html", "sem_8c" ],
    [ "sem.h", "sem_8h.html", "sem_8h" ],
    [ "util.c", "util_8c.html", "util_8c" ],
    [ "util.h", "util_8h.html", "util_8h" ],
    [ "version.c.in", "version_8c_8in.html", null ],
    [ "version.h", "version_8h.html", "version_8h" ]
];