RocketLogger: gpiod_test.c File Reference
gpiod_test.c File Reference
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <gpiod.h>
#include <unistd.h>
#include "gpio.hpp"
Macros
#define GPIO_FHR1 30
Linux sysfs GPIO number for forcing I1 high.
#define GPIO_FHR2 60
Linux sysfs GPIO number for forcing I2 high.
#define GPIO_LED_STATUS 45
Linux sysfs GPIO number of status LED.
#define GPIO_LED_ERROR 44
Linux sysfs GPIO number of error LED.
#define GPIO_BUTTON 26
Linux sysfs GPIO number of start/stop button.
#define GPIO_POWER 31
Linux sysfs GPIO number of RocketLogger cape power enable.
Functions
int main (void)
Macro Definition Documentation
GPIO_BUTTON
#define GPIO_BUTTON 26
Linux sysfs GPIO number of start/stop button.
Definition at line 21 of file gpiod_test.c.
GPIO_FHR1
#define GPIO_FHR1 30
Linux sysfs GPIO number for forcing I1 high.
Definition at line 13 of file gpiod_test.c.
GPIO_FHR2
#define GPIO_FHR2 60
Linux sysfs GPIO number for forcing I2 high.
Definition at line 15 of file gpiod_test.c.
GPIO_LED_ERROR
#define GPIO_LED_ERROR 44
Linux sysfs GPIO number of error LED.
Definition at line 19 of file gpiod_test.c.
GPIO_LED_STATUS
#define GPIO_LED_STATUS 45
Linux sysfs GPIO number of status LED.
Definition at line 17 of file gpiod_test.c.
GPIO_POWER
#define GPIO_POWER 31
Linux sysfs GPIO number of RocketLogger cape power enable.
Definition at line 23 of file gpiod_test.c.
Function Documentation
main()
int main (void)
Definition at line 43 of file gpiod_test.c.
References GPIO_BUTTON, gpio_button, gpio_deinit(), gpio_init(), GPIO_INTERRUPT_BOTH, GPIO_LED_ERROR, GPIO_LED_STATUS, GPIO_MODE_OUT, GPIO_POWER, gpio_release(), gpio_set_value(), gpio_setup(), gpio_setup_interrupt(), and gpio_wait_interrupt().