RocketLogger: sem.h File Reference
sem.h File Reference
#include <sys/types.h>
Macros
#define SEM_KEY 2222
Semaphore key (used for set creation)
#define SEM_OPT_NO_FLAG 0
Time out time in seconds, waiting on semaphore write.
#define SEM_TIMEOUT_READ 3
Time out time in seconds, waiting on semaphore read.
#define SEM_TIMEOUT_WRITE 1
Time out time in seconds, waiting on semaphore write.
#define SEM_SEM_COUNT 2
Total number of semaphores in set.
#define SEM_INDEX_DATA 0
Index of the data semaphore (protects shared memory accesses)
#define SEM_INDEX_WAIT 1
Index of the wait semaphore (blocks until new data is available)
Functions
int sem_create (key_t key, int count)
int sem_remove (int id)
int sem_open (key_t key, int count)
int sem_wait (int id, int index, int timeout)
int sem_set (int id, int index, int value)
int sem_get (int id, int index)
Macro Definition Documentation
SEM_INDEX_DATA
#define SEM_INDEX_DATA 0
Index of the data semaphore (protects shared memory accesses)
Definition at line 49 of file sem.h.
SEM_INDEX_WAIT
#define SEM_INDEX_WAIT 1
Index of the wait semaphore (blocks until new data is available)
Definition at line 51 of file sem.h.
SEM_KEY
#define SEM_KEY 2222
Semaphore key (used for set creation)
Copyright (c) 2016-2020, ETH Zurich, Computer Engineering Group All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 38 of file sem.h.
SEM_OPT_NO_FLAG
#define SEM_OPT_NO_FLAG 0
Time out time in seconds, waiting on semaphore write.
Definition at line 40 of file sem.h.
SEM_SEM_COUNT
#define SEM_SEM_COUNT 2
Total number of semaphores in set.
Definition at line 47 of file sem.h.
SEM_TIMEOUT_READ
#define SEM_TIMEOUT_READ 3
Time out time in seconds, waiting on semaphore read.
Definition at line 42 of file sem.h.
SEM_TIMEOUT_WRITE
#define SEM_TIMEOUT_WRITE 1
Time out time in seconds, waiting on semaphore write.
Definition at line 44 of file sem.h.
Function Documentation
sem_create()
int sem_create (key_t key, int count)
Create RocketLogger semaphore set.
Parameters
key The key identifying the semaphore set to create
count The number of semaphores in the set to create
Returns
ID of created set on success, negative on failure with errno set accordingly
Definition at line 49 of file sem.c.
References rl_log(), and RL_LOG_ERROR.
sem_get()
int sem_get (int id, int index)
Get value of a semaphore.
Parameters
id ID of semaphore set
index Index of semaphore in set
Returns
The semaphore count, or negative on failure with errno set accordingly
Definition at line 129 of file sem.c.
References rl_log(), and RL_LOG_ERROR.
sem_open()
int sem_open (key_t key, int count)
Open existing RocketLogger semaphore set.
Parameters
key The key identifying the semaphore set
count The number of semaphores in the set
Returns
ID of opened set, negative on failure with errno set accordingly
Definition at line 68 of file sem.c.
References rl_log(), and RL_LOG_ERROR.
sem_remove()
int sem_remove (int id)
Remove semaphore set.
Parameters
id ID of set to remove
Returns
Returns 0 on success, negative on failure with errno set accordingly
Definition at line 58 of file sem.c.
References rl_log(), RL_LOG_ERROR, and SUCCESS.
sem_set()
int sem_set (int id, int index, int value)
Set value to semaphore.
Parameters
id ID of semaphore set
index Index of semaphore in set
value Value to be set to semaphore
Returns
Returns 0 on success, negative on failure with errno set accordingly
Definition at line 108 of file sem.c.
References rl_log(), RL_LOG_ERROR, SEM_OPT_NO_FLAG, SEM_TIMEOUT_WRITE, and SUCCESS.
sem_wait()
int sem_wait (int id, int index, int timeout)
Wait on a semaphore until access granted.
Parameters
id ID of semaphore set
index Index of semaphore in set
timeout Maximum waiting time before failing in seconds
Returns
Returns 0 on success, negative on failure with errno set accordingly
Definition at line 78 of file sem.c.
References rl_log(), RL_LOG_ERROR, SEM_OPT_NO_FLAG, and SUCCESS.