RocketLogger: util.h File Reference
util.h File Reference
#include <stdbool.h>
#include <stdint.h>
#include "rl.h"
Data Structures
struct rl_timestamp
Macros
#define MAC_ADDRESS_LENGTH 6
MAC address length in bytes.
#define MAC_ADDRESS_FILE "/sys/class/net/eth0/address"
File to read MAC address.
Typedefs
typedef struct rl_timestamp rl_timestamp_t
Functions
bool is_current (int index)
bool is_low_current (int index)
bool is_voltage (int index)
bool is_empty_string (char const *str)
bool is_printable_string (char const *str)
int count_channels (bool const channels[RL_CHANNEL_COUNT])
int div_ceil (int n, int d)
void create_time_stamp (rl_timestamp_t *const time_realtime, rl_timestamp_t *const time_monotonic)
void get_mac_addr (uint8_t mac_address[MAC_ADDRESS_LENGTH])
int64_t fs_space_total (char const *const path)
int64_t fs_space_free (char const *const path)
void print_json_bool (bool const *const data, const int length)
void print_json_int64 (int64_t const *const data, const int length)
int snprintfcat (char *const buffer, size_t length, char const *format,...)
Macro Definition Documentation
MAC_ADDRESS_FILE
#define MAC_ADDRESS_FILE "/sys/class/net/eth0/address"
File to read MAC address.
Definition at line 44 of file util.h.
MAC_ADDRESS_LENGTH
#define MAC_ADDRESS_LENGTH 6
MAC address length in bytes.
Copyright (c) 2016-2020, ETH Zurich, Computer Engineering Group All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 41 of file util.h.
Typedef Documentation
rl_timestamp_t
typedef struct rl_timestamp rl_timestamp_t
Typedef for timestamp structure
Definition at line 59 of file util.h.
Function Documentation
count_channels()
int count_channels (bool const channels[RL_CHANNEL_COUNT])
Counts the number of channels enabled.
Parameters
channels Channel enable array
Returns
The number of enabled channels
Definition at line 72 of file util.c.
References RL_CHANNEL_COUNT.
Referenced by hw_init(), and rl_file_setup_data_lead_in().
create_time_stamp()
void create_time_stamp (rl_timestamp_t *const time_realtime, rl_timestamp_t *const time_monotonic)
Create time stamps (real-time and monotonic).
Parameters
timestamp_realtime Timestamp data structure to store the time value read from the real-time clock to
timestamp_monotonic Timestamp data structure to store the time value read from the monotonic clock to
Definition at line 90 of file util.c.
References rl_timestamp::nsec, rl_log(), RL_LOG_ERROR, and rl_timestamp::sec.
Referenced by pru_sample(), rl_file_setup_ambient_lead_in(), and rl_file_setup_data_lead_in().
div_ceil()
int div_ceil (int n, int d)
Integer division with ceiling.
Parameters
n Numerator
d Denominator
Returns
Division result rounded up to next integer
Definition at line 82 of file util.c.
Referenced by pru_sample().
fs_space_free()
int64_t fs_space_free (char const *const path)
Get free disk space in a directory in bytes.
Parameters
path Path to selected directory
Returns
Free disk space in bytes
Definition at line 125 of file util.c.
References rl_log(), and RL_LOG_WARNING.
Referenced by rl_get_status(), and rl_status_write().
fs_space_total()
int64_t fs_space_total (char const *const path)
Get total disk space in a directory in bytes.
Parameters
path Path to selected directory
Returns
Total disk space in bytes
Definition at line 137 of file util.c.
References rl_log(), and RL_LOG_WARNING.
Referenced by rl_get_status(), and rl_status_write().
get_mac_addr()
void get_mac_addr (uint8_t mac_address[MAC_ADDRESS_LENGTH])
Get MAC address of network device.
Parameters
mac_address Array to write the MAC address to
Definition at line 112 of file util.c.
References MAC_ADDRESS_FILE, and MAC_ADDRESS_LENGTH.
Referenced by rl_file_setup_ambient_lead_in(), and rl_file_setup_data_lead_in().
is_current()
bool is_current (int index)
Checks whether a channel is a current channel.
Parameters
index Index of channel in array
Returns
Returns true if channel is a current, false otherwise
Copyright (c) 2016-2020, ETH Zurich, Computer Engineering Group All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition at line 49 of file util.c.
References RL_CONFIG_CHANNEL_I1H, RL_CONFIG_CHANNEL_I1L, RL_CONFIG_CHANNEL_I2H, and RL_CONFIG_CHANNEL_I2L.
Referenced by meter_print_buffer(), rl_file_setup_data_channels(), and rl_socket_metadata().
is_empty_string()
bool is_empty_string (char const * str)
Check whether a string is empty, i.e. does not contain visible characters.
Validates to true if none of the characters belongs to either isgraph()
Parameters
str The string to validate
Returns
True if string is empty, false otherwise
Definition at line 149 of file util.c.
is_low_current()
bool is_low_current (int index)
Checks whether a channel is a low range current channel.
Parameters
index Index of channel in array
Returns
Returns true if channel is a low range current, false otherwise
Definition at line 57 of file util.c.
References RL_CONFIG_CHANNEL_I1L, and RL_CONFIG_CHANNEL_I2L.
Referenced by rl_file_setup_data_channels(), and rl_socket_metadata().
is_printable_string()
bool is_printable_string (char const * str)
Check whether a string is printable.
Validates to true if all characters belong to either isspace() or isprint()
Parameters
str The string to validate
Returns
True if string is printable, false otherwise
Definition at line 158 of file util.c.
Referenced by rl_config_validate().
is_voltage()
bool is_voltage (int index)
Checks whether a channel is a voltage channel.
Parameters
index Index of channel in array
Returns
Returns true if channel is a voltage, false otherwise
Definition at line 64 of file util.c.
References RL_CONFIG_CHANNEL_V1, RL_CONFIG_CHANNEL_V2, RL_CONFIG_CHANNEL_V3, and RL_CONFIG_CHANNEL_V4.
Referenced by rl_file_setup_data_channels(), and rl_socket_metadata().
print_json_bool()
void print_json_bool (bool const *const data, const int length)
Print a boolean array in JSON format.
Parameters
data Data array to print
length Length of array
Definition at line 169 of file util.c.
References data.
print_json_int64()
void print_json_int64 (int64_t const *const data, const int length)
Print a 64-bit integer array in JSON format.
Parameters
data Data array to print
length Length of array
Definition at line 180 of file util.c.
References data.
snprintfcat()
int snprintfcat (char *const buffer, size_t length, char const * format, ...)
Append formatted string to setting line with formated string value.
Parameters
buffer The string buffer to append the formatted string to
length Maximum length of the buffer
format Formatting string passed to snprintf()
... Variables used to format string
Definition at line 191 of file util.c.
Referenced by rl_config_get_json(), rl_socket_metadata(), and rl_status_get_json().