RocketLogger: log.c File Reference
log.c File Reference
#include "log.h"
Functions
void rl_log (rl_log_type type, const char *format,...)
Function Documentation
void rl_log (rl_log_type type, const char * format, ...)
Copyright (c) 2016-2019, Swiss Federal Institute of Technology (ETH Zurich) All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. Log a message.
Parameters
type Type of message.
format Message format.
Definition at line 39 of file log.c.
References ERROR, INFO, LOG_FILE, MAX_LOG_FILE_SIZE, RL_ERROR, rl_status::state, status, and WARNING.
Referenced by BME280_getID(), BME280_init(), BME280_read(), BME280_readCalibration(), BME280_setParameters(), create_sem(), create_time_stamp(), file_handle_data(), gpio_dir(), gpio_export(), gpio_get_value(), gpio_interrupt(), gpio_set_value(), gpio_unexport(), gpio_wait_interrupt(), hw_sample(), main(), open_sem(), parse_args(), parse_channels(), print_data(), pru_data_setup(), pru_init(), pru_map_memory(), pru_sample(), pru_unmap_memory(), pwm_setup(), read_default_config(), read_file_value(), read_status(), remove_sem(), rl_start(), rl_stop(), Sensors_closeBus(), Sensors_openBus(), Sensors_scan(), set_pid(), set_sem(), TSL4531_getID(), TSL4531_init(), TSL4531_read(), TSL4531_sendRange(), TSL4531_setParameters(), TSL4531_setRange(), wait_sem(), web_create_shm(), web_handle_data(), web_open_shm(), write_default_config(), and write_status().