RocketLogger: rl_deamon.c File Reference
rl_deamon.c File Reference
#include "gpio.h"
Macros
#define GPIO_BUTTON 26
Linux GPIO number of start/stop button.
#define MIN_INTERVAL 1
Minimal time interval between two interrupts (in seconds)
Functions
int gpio_setup (void)
void interrupt_handler (int value)
int main (void)
Macro Definition Documentation
#define GPIO_BUTTON 26
Linux GPIO number of start/stop button.
Copyright (c) 2016-2017, ETH Zurich, Computer Engineering Group
Definition at line 8 of file rl_deamon.c.
Referenced by gpio_setup(), and main().
#define MIN_INTERVAL 1
Minimal time interval between two interrupts (in seconds)
Definition at line 10 of file rl_deamon.c.
Referenced by interrupt_handler().
Function Documentation
int gpio_setup (void)
Setup button GPIO
Returns
SUCCESS on success, FAILURE otherwise
Definition at line 16 of file rl_deamon.c.
References FAILURE, FALLING, GPIO_BUTTON, gpio_dir(), gpio_export(), gpio_interrupt(), IN, and SUCCESS.
Referenced by main().
void interrupt_handler (int value)
GPIO interrupt handler
Parameters
value GPIO value after interrupt
Definition at line 33 of file rl_deamon.c.
References MIN_INTERVAL, and status.
Referenced by main().
int main (void)
RocketLogger deamon program. Continuously waits on interrupt on button GPIO and starts/stops RocketLogger
Arguments: none
Returns
standard Linux return codes
Definition at line 59 of file rl_deamon.c.
References FAILURE, GPIO_BUTTON, gpio_setup(), gpio_wait_interrupt(), and interrupt_handler().