# GitHub Actions config to generate Doxygen and Sphinx documentation and publish to GitHub Pages

name: Publish documentation

# Controls when the workflow will run
on:
  # Triggers the workflow when creating a release
  release:
    types:
      - created

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a two jobs called "build"
  build-doxygen:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare git revision info
        id: git_info
        run: |
          echo ::set-output name=NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Build docs
        uses: mattnotmitt/doxygen-action@v1
        with:
          working-directory: software/rocketlogger

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: software/rocketlogger/docs/html
          destination_dir: software/${{ steps.git_info.outputs.NAME }}
          enable_jekyll: true

  # This workflow contains a two jobs called "build"
  build-sphinx:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: script/python

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Prepare git revision info
        id: git_info
        run: |
          echo ::set-output name=NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=TAG::${GITHUB_REF#refs/tags/}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build docs
        run: |
          python setup.py build_sphinx -a

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: script/python/build/sphinx/html
          destination_dir: python/${{ steps.git_info.outputs.NAME }}
          enable_jekyll: true
